//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace co.itmasters.solucion.web.OfertaService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="OfertaService.IOfertaService")]
    public interface IOfertaService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOfertaService/Postulados", ReplyAction="http://tempuri.org/IOfertaService/PostuladosResponse")]
        co.itmasters.solucion.vo.PersonaVO[] Postulados(co.itmasters.solucion.vo.OfertaVO oferta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOfertaService/Postulados", ReplyAction="http://tempuri.org/IOfertaService/PostuladosResponse")]
        System.Threading.Tasks.Task<co.itmasters.solucion.vo.PersonaVO[]> PostuladosAsync(co.itmasters.solucion.vo.OfertaVO oferta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOfertaService/Postulacion", ReplyAction="http://tempuri.org/IOfertaService/PostulacionResponse")]
        void Postulacion([System.ServiceModel.MessageParameterAttribute(Name="postulacion")] co.itmasters.solucion.vo.OfertaVO postulacion1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOfertaService/Postulacion", ReplyAction="http://tempuri.org/IOfertaService/PostulacionResponse")]
        System.Threading.Tasks.Task PostulacionAsync(co.itmasters.solucion.vo.OfertaVO postulacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOfertaService/TraePlanesAdquiridosEmpresa", ReplyAction="http://tempuri.org/IOfertaService/TraePlanesAdquiridosEmpresaResponse")]
        co.itmasters.solucion.vo.OfertaVO[] TraePlanesAdquiridosEmpresa(co.itmasters.solucion.vo.OfertaVO Oferta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOfertaService/TraePlanesAdquiridosEmpresa", ReplyAction="http://tempuri.org/IOfertaService/TraePlanesAdquiridosEmpresaResponse")]
        System.Threading.Tasks.Task<co.itmasters.solucion.vo.OfertaVO[]> TraePlanesAdquiridosEmpresaAsync(co.itmasters.solucion.vo.OfertaVO Oferta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOfertaService/GetOfertaPersonaDetalle", ReplyAction="http://tempuri.org/IOfertaService/GetOfertaPersonaDetalleResponse")]
        co.itmasters.solucion.vo.OfertaVO GetOfertaPersonaDetalle(co.itmasters.solucion.vo.OfertaVO Ofertas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOfertaService/GetOfertaPersonaDetalle", ReplyAction="http://tempuri.org/IOfertaService/GetOfertaPersonaDetalleResponse")]
        System.Threading.Tasks.Task<co.itmasters.solucion.vo.OfertaVO> GetOfertaPersonaDetalleAsync(co.itmasters.solucion.vo.OfertaVO Ofertas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOfertaService/GetOfertaPersona", ReplyAction="http://tempuri.org/IOfertaService/GetOfertaPersonaResponse")]
        co.itmasters.solucion.vo.OfertaVO[] GetOfertaPersona(co.itmasters.solucion.vo.OfertaVO Ofertas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOfertaService/GetOfertaPersona", ReplyAction="http://tempuri.org/IOfertaService/GetOfertaPersonaResponse")]
        System.Threading.Tasks.Task<co.itmasters.solucion.vo.OfertaVO[]> GetOfertaPersonaAsync(co.itmasters.solucion.vo.OfertaVO Ofertas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOfertaService/TraeOfertaDetalle", ReplyAction="http://tempuri.org/IOfertaService/TraeOfertaDetalleResponse")]
        co.itmasters.solucion.vo.OfertaVO TraeOfertaDetalle(co.itmasters.solucion.vo.OfertaVO Ofertas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOfertaService/TraeOfertaDetalle", ReplyAction="http://tempuri.org/IOfertaService/TraeOfertaDetalleResponse")]
        System.Threading.Tasks.Task<co.itmasters.solucion.vo.OfertaVO> TraeOfertaDetalleAsync(co.itmasters.solucion.vo.OfertaVO Ofertas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOfertaService/TraerEstadisticasOferta", ReplyAction="http://tempuri.org/IOfertaService/TraerEstadisticasOfertaResponse")]
        co.itmasters.solucion.vo.OfertaVO TraerEstadisticasOferta(co.itmasters.solucion.vo.OfertaVO Ofertas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOfertaService/TraerEstadisticasOferta", ReplyAction="http://tempuri.org/IOfertaService/TraerEstadisticasOfertaResponse")]
        System.Threading.Tasks.Task<co.itmasters.solucion.vo.OfertaVO> TraerEstadisticasOfertaAsync(co.itmasters.solucion.vo.OfertaVO Ofertas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOfertaService/TraeOfertaEmpresa", ReplyAction="http://tempuri.org/IOfertaService/TraeOfertaEmpresaResponse")]
        co.itmasters.solucion.vo.OfertaVO[] TraeOfertaEmpresa(co.itmasters.solucion.vo.OfertaVO Ofertas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOfertaService/TraeOfertaEmpresa", ReplyAction="http://tempuri.org/IOfertaService/TraeOfertaEmpresaResponse")]
        System.Threading.Tasks.Task<co.itmasters.solucion.vo.OfertaVO[]> TraeOfertaEmpresaAsync(co.itmasters.solucion.vo.OfertaVO Ofertas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOfertaService/TraeEstadoOfertaEmpresa", ReplyAction="http://tempuri.org/IOfertaService/TraeEstadoOfertaEmpresaResponse")]
        co.itmasters.solucion.vo.OfertaVO[] TraeEstadoOfertaEmpresa(co.itmasters.solucion.vo.OfertaVO Estado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOfertaService/TraeEstadoOfertaEmpresa", ReplyAction="http://tempuri.org/IOfertaService/TraeEstadoOfertaEmpresaResponse")]
        System.Threading.Tasks.Task<co.itmasters.solucion.vo.OfertaVO[]> TraeEstadoOfertaEmpresaAsync(co.itmasters.solucion.vo.OfertaVO Estado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOfertaService/TraeEstadoOferta", ReplyAction="http://tempuri.org/IOfertaService/TraeEstadoOfertaResponse")]
        co.itmasters.solucion.vo.OfertaVO[] TraeEstadoOferta(co.itmasters.solucion.vo.OfertaVO Estado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOfertaService/TraeEstadoOferta", ReplyAction="http://tempuri.org/IOfertaService/TraeEstadoOfertaResponse")]
        System.Threading.Tasks.Task<co.itmasters.solucion.vo.OfertaVO[]> TraeEstadoOfertaAsync(co.itmasters.solucion.vo.OfertaVO Estado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOfertaService/AnulaOferta", ReplyAction="http://tempuri.org/IOfertaService/AnulaOfertaResponse")]
        void AnulaOferta(co.itmasters.solucion.vo.OfertaVO Oferta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOfertaService/AnulaOferta", ReplyAction="http://tempuri.org/IOfertaService/AnulaOfertaResponse")]
        System.Threading.Tasks.Task AnulaOfertaAsync(co.itmasters.solucion.vo.OfertaVO Oferta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOfertaService/PublicarOferta", ReplyAction="http://tempuri.org/IOfertaService/PublicarOfertaResponse")]
        void PublicarOferta(co.itmasters.solucion.vo.OfertaVO Oferta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOfertaService/PublicarOferta", ReplyAction="http://tempuri.org/IOfertaService/PublicarOfertaResponse")]
        System.Threading.Tasks.Task PublicarOfertaAsync(co.itmasters.solucion.vo.OfertaVO Oferta);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IOfertaServiceChannel : co.itmasters.solucion.web.OfertaService.IOfertaService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OfertaServiceClient : System.ServiceModel.ClientBase<co.itmasters.solucion.web.OfertaService.IOfertaService>, co.itmasters.solucion.web.OfertaService.IOfertaService {
        
        public OfertaServiceClient() {
        }
        
        public OfertaServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OfertaServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OfertaServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OfertaServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public co.itmasters.solucion.vo.PersonaVO[] Postulados(co.itmasters.solucion.vo.OfertaVO oferta) {
            return base.Channel.Postulados(oferta);
        }
        
        public System.Threading.Tasks.Task<co.itmasters.solucion.vo.PersonaVO[]> PostuladosAsync(co.itmasters.solucion.vo.OfertaVO oferta) {
            return base.Channel.PostuladosAsync(oferta);
        }
        
        public void Postulacion(co.itmasters.solucion.vo.OfertaVO postulacion1) {
            base.Channel.Postulacion(postulacion1);
        }
        
        public System.Threading.Tasks.Task PostulacionAsync(co.itmasters.solucion.vo.OfertaVO postulacion) {
            return base.Channel.PostulacionAsync(postulacion);
        }
        
        public co.itmasters.solucion.vo.OfertaVO[] TraePlanesAdquiridosEmpresa(co.itmasters.solucion.vo.OfertaVO Oferta) {
            return base.Channel.TraePlanesAdquiridosEmpresa(Oferta);
        }
        
        public System.Threading.Tasks.Task<co.itmasters.solucion.vo.OfertaVO[]> TraePlanesAdquiridosEmpresaAsync(co.itmasters.solucion.vo.OfertaVO Oferta) {
            return base.Channel.TraePlanesAdquiridosEmpresaAsync(Oferta);
        }
        
        public co.itmasters.solucion.vo.OfertaVO GetOfertaPersonaDetalle(co.itmasters.solucion.vo.OfertaVO Ofertas) {
            return base.Channel.GetOfertaPersonaDetalle(Ofertas);
        }
        
        public System.Threading.Tasks.Task<co.itmasters.solucion.vo.OfertaVO> GetOfertaPersonaDetalleAsync(co.itmasters.solucion.vo.OfertaVO Ofertas) {
            return base.Channel.GetOfertaPersonaDetalleAsync(Ofertas);
        }
        
        public co.itmasters.solucion.vo.OfertaVO[] GetOfertaPersona(co.itmasters.solucion.vo.OfertaVO Ofertas) {
            return base.Channel.GetOfertaPersona(Ofertas);
        }
        
        public System.Threading.Tasks.Task<co.itmasters.solucion.vo.OfertaVO[]> GetOfertaPersonaAsync(co.itmasters.solucion.vo.OfertaVO Ofertas) {
            return base.Channel.GetOfertaPersonaAsync(Ofertas);
        }
        
        public co.itmasters.solucion.vo.OfertaVO TraeOfertaDetalle(co.itmasters.solucion.vo.OfertaVO Ofertas) {
            return base.Channel.TraeOfertaDetalle(Ofertas);
        }
        
        public System.Threading.Tasks.Task<co.itmasters.solucion.vo.OfertaVO> TraeOfertaDetalleAsync(co.itmasters.solucion.vo.OfertaVO Ofertas) {
            return base.Channel.TraeOfertaDetalleAsync(Ofertas);
        }
        
        public co.itmasters.solucion.vo.OfertaVO TraerEstadisticasOferta(co.itmasters.solucion.vo.OfertaVO Ofertas) {
            return base.Channel.TraerEstadisticasOferta(Ofertas);
        }
        
        public System.Threading.Tasks.Task<co.itmasters.solucion.vo.OfertaVO> TraerEstadisticasOfertaAsync(co.itmasters.solucion.vo.OfertaVO Ofertas) {
            return base.Channel.TraerEstadisticasOfertaAsync(Ofertas);
        }
        
        public co.itmasters.solucion.vo.OfertaVO[] TraeOfertaEmpresa(co.itmasters.solucion.vo.OfertaVO Ofertas) {
            return base.Channel.TraeOfertaEmpresa(Ofertas);
        }
        
        public System.Threading.Tasks.Task<co.itmasters.solucion.vo.OfertaVO[]> TraeOfertaEmpresaAsync(co.itmasters.solucion.vo.OfertaVO Ofertas) {
            return base.Channel.TraeOfertaEmpresaAsync(Ofertas);
        }
        
        public co.itmasters.solucion.vo.OfertaVO[] TraeEstadoOfertaEmpresa(co.itmasters.solucion.vo.OfertaVO Estado) {
            return base.Channel.TraeEstadoOfertaEmpresa(Estado);
        }
        
        public System.Threading.Tasks.Task<co.itmasters.solucion.vo.OfertaVO[]> TraeEstadoOfertaEmpresaAsync(co.itmasters.solucion.vo.OfertaVO Estado) {
            return base.Channel.TraeEstadoOfertaEmpresaAsync(Estado);
        }
        
        public co.itmasters.solucion.vo.OfertaVO[] TraeEstadoOferta(co.itmasters.solucion.vo.OfertaVO Estado) {
            return base.Channel.TraeEstadoOferta(Estado);
        }
        
        public System.Threading.Tasks.Task<co.itmasters.solucion.vo.OfertaVO[]> TraeEstadoOfertaAsync(co.itmasters.solucion.vo.OfertaVO Estado) {
            return base.Channel.TraeEstadoOfertaAsync(Estado);
        }
        
        public void AnulaOferta(co.itmasters.solucion.vo.OfertaVO Oferta) {
            base.Channel.AnulaOferta(Oferta);
        }
        
        public System.Threading.Tasks.Task AnulaOfertaAsync(co.itmasters.solucion.vo.OfertaVO Oferta) {
            return base.Channel.AnulaOfertaAsync(Oferta);
        }
        
        public void PublicarOferta(co.itmasters.solucion.vo.OfertaVO Oferta) {
            base.Channel.PublicarOferta(Oferta);
        }
        
        public System.Threading.Tasks.Task PublicarOfertaAsync(co.itmasters.solucion.vo.OfertaVO Oferta) {
            return base.Channel.PublicarOfertaAsync(Oferta);
        }
    }
}
