//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace co.itmasters.solucion.web.EmpresaService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EmpresaService.IEmpresaService")]
    public interface IEmpresaService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmpresaService/CreatePlanAdquirido", ReplyAction="http://tempuri.org/IEmpresaService/CreatePlanAdquiridoResponse")]
        string CreatePlanAdquirido(co.itmasters.solucion.vo.EmpresaVO empresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmpresaService/CreatePlanAdquirido", ReplyAction="http://tempuri.org/IEmpresaService/CreatePlanAdquiridoResponse")]
        System.Threading.Tasks.Task<string> CreatePlanAdquiridoAsync(co.itmasters.solucion.vo.EmpresaVO empresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmpresaService/GuardarDatosEmpresa", ReplyAction="http://tempuri.org/IEmpresaService/GuardarDatosEmpresaResponse")]
        void GuardarDatosEmpresa(co.itmasters.solucion.vo.EmpresaVO Empresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmpresaService/GuardarDatosEmpresa", ReplyAction="http://tempuri.org/IEmpresaService/GuardarDatosEmpresaResponse")]
        System.Threading.Tasks.Task GuardarDatosEmpresaAsync(co.itmasters.solucion.vo.EmpresaVO Empresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmpresaService/TraeEmpresas", ReplyAction="http://tempuri.org/IEmpresaService/TraeEmpresasResponse")]
        co.itmasters.solucion.vo.EmpresaVO[] TraeEmpresas(co.itmasters.solucion.vo.EmpresaVO empresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmpresaService/TraeEmpresas", ReplyAction="http://tempuri.org/IEmpresaService/TraeEmpresasResponse")]
        System.Threading.Tasks.Task<co.itmasters.solucion.vo.EmpresaVO[]> TraeEmpresasAsync(co.itmasters.solucion.vo.EmpresaVO empresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmpresaService/DatosEmpresa", ReplyAction="http://tempuri.org/IEmpresaService/DatosEmpresaResponse")]
        co.itmasters.solucion.vo.EmpresaVO DatosEmpresa(co.itmasters.solucion.vo.EmpresaVO Empresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmpresaService/DatosEmpresa", ReplyAction="http://tempuri.org/IEmpresaService/DatosEmpresaResponse")]
        System.Threading.Tasks.Task<co.itmasters.solucion.vo.EmpresaVO> DatosEmpresaAsync(co.itmasters.solucion.vo.EmpresaVO Empresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmpresaService/AprobarEmpresas", ReplyAction="http://tempuri.org/IEmpresaService/AprobarEmpresasResponse")]
        void AprobarEmpresas(co.itmasters.solucion.vo.EmpresaVO Empresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmpresaService/AprobarEmpresas", ReplyAction="http://tempuri.org/IEmpresaService/AprobarEmpresasResponse")]
        System.Threading.Tasks.Task AprobarEmpresasAsync(co.itmasters.solucion.vo.EmpresaVO Empresa);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEmpresaServiceChannel : co.itmasters.solucion.web.EmpresaService.IEmpresaService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EmpresaServiceClient : System.ServiceModel.ClientBase<co.itmasters.solucion.web.EmpresaService.IEmpresaService>, co.itmasters.solucion.web.EmpresaService.IEmpresaService {
        
        public EmpresaServiceClient() {
        }
        
        public EmpresaServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EmpresaServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmpresaServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmpresaServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string CreatePlanAdquirido(co.itmasters.solucion.vo.EmpresaVO empresa) {
            return base.Channel.CreatePlanAdquirido(empresa);
        }
        
        public System.Threading.Tasks.Task<string> CreatePlanAdquiridoAsync(co.itmasters.solucion.vo.EmpresaVO empresa) {
            return base.Channel.CreatePlanAdquiridoAsync(empresa);
        }
        
        public void GuardarDatosEmpresa(co.itmasters.solucion.vo.EmpresaVO Empresa) {
            base.Channel.GuardarDatosEmpresa(Empresa);
        }
        
        public System.Threading.Tasks.Task GuardarDatosEmpresaAsync(co.itmasters.solucion.vo.EmpresaVO Empresa) {
            return base.Channel.GuardarDatosEmpresaAsync(Empresa);
        }
        
        public co.itmasters.solucion.vo.EmpresaVO[] TraeEmpresas(co.itmasters.solucion.vo.EmpresaVO empresa) {
            return base.Channel.TraeEmpresas(empresa);
        }
        
        public System.Threading.Tasks.Task<co.itmasters.solucion.vo.EmpresaVO[]> TraeEmpresasAsync(co.itmasters.solucion.vo.EmpresaVO empresa) {
            return base.Channel.TraeEmpresasAsync(empresa);
        }
        
        public co.itmasters.solucion.vo.EmpresaVO DatosEmpresa(co.itmasters.solucion.vo.EmpresaVO Empresa) {
            return base.Channel.DatosEmpresa(Empresa);
        }
        
        public System.Threading.Tasks.Task<co.itmasters.solucion.vo.EmpresaVO> DatosEmpresaAsync(co.itmasters.solucion.vo.EmpresaVO Empresa) {
            return base.Channel.DatosEmpresaAsync(Empresa);
        }
        
        public void AprobarEmpresas(co.itmasters.solucion.vo.EmpresaVO Empresa) {
            base.Channel.AprobarEmpresas(Empresa);
        }
        
        public System.Threading.Tasks.Task AprobarEmpresasAsync(co.itmasters.solucion.vo.EmpresaVO Empresa) {
            return base.Channel.AprobarEmpresasAsync(Empresa);
        }
    }
}
