//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace co.itmasters.solucion.web.PersonaService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PersonaService.IPersonaService")]
    public interface IPersonaService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonaService/PersonaDatosBasicos_Update", ReplyAction="http://tempuri.org/IPersonaService/PersonaDatosBasicos_UpdateResponse")]
        void PersonaDatosBasicos_Update(co.itmasters.solucion.vo.PersonaVO pPersona);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonaService/PersonaDatosBasicos_Update", ReplyAction="http://tempuri.org/IPersonaService/PersonaDatosBasicos_UpdateResponse")]
        System.Threading.Tasks.Task PersonaDatosBasicos_UpdateAsync(co.itmasters.solucion.vo.PersonaVO pPersona);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonaService/PersonaAcademia_Update", ReplyAction="http://tempuri.org/IPersonaService/PersonaAcademia_UpdateResponse")]
        void PersonaAcademia_Update(co.itmasters.solucion.vo.PersonaAcademiaVO pPersona);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonaService/PersonaAcademia_Update", ReplyAction="http://tempuri.org/IPersonaService/PersonaAcademia_UpdateResponse")]
        System.Threading.Tasks.Task PersonaAcademia_UpdateAsync(co.itmasters.solucion.vo.PersonaAcademiaVO pPersona);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonaService/PersonaExperiencia_Update", ReplyAction="http://tempuri.org/IPersonaService/PersonaExperiencia_UpdateResponse")]
        void PersonaExperiencia_Update(co.itmasters.solucion.vo.PersonaExperienciaVO pPersona);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonaService/PersonaExperiencia_Update", ReplyAction="http://tempuri.org/IPersonaService/PersonaExperiencia_UpdateResponse")]
        System.Threading.Tasks.Task PersonaExperiencia_UpdateAsync(co.itmasters.solucion.vo.PersonaExperienciaVO pPersona);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonaService/PersonaAptitud_Update", ReplyAction="http://tempuri.org/IPersonaService/PersonaAptitud_UpdateResponse")]
        void PersonaAptitud_Update(co.itmasters.solucion.vo.PersonaAptitudVO pPersona);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonaService/PersonaAptitud_Update", ReplyAction="http://tempuri.org/IPersonaService/PersonaAptitud_UpdateResponse")]
        System.Threading.Tasks.Task PersonaAptitud_UpdateAsync(co.itmasters.solucion.vo.PersonaAptitudVO pPersona);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonaService/ActEconomicaAutocomplete", ReplyAction="http://tempuri.org/IPersonaService/ActEconomicaAutocompleteResponse")]
        co.itmasters.solucion.vo.AutocompleteActividadEconomica[] ActEconomicaAutocomplete(co.itmasters.solucion.vo.AutocompleteActividadEconomica Act);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonaService/ActEconomicaAutocomplete", ReplyAction="http://tempuri.org/IPersonaService/ActEconomicaAutocompleteResponse")]
        System.Threading.Tasks.Task<co.itmasters.solucion.vo.AutocompleteActividadEconomica[]> ActEconomicaAutocompleteAsync(co.itmasters.solucion.vo.AutocompleteActividadEconomica Act);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonaService/CiudadDepartamentoPaisForm", ReplyAction="http://tempuri.org/IPersonaService/CiudadDepartamentoPaisFormResponse")]
        co.itmasters.solucion.vo.AutocompleteFormulario CiudadDepartamentoPaisForm(co.itmasters.solucion.vo.AutocompleteFormulario Autocomplete);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonaService/CiudadDepartamentoPaisForm", ReplyAction="http://tempuri.org/IPersonaService/CiudadDepartamentoPaisFormResponse")]
        System.Threading.Tasks.Task<co.itmasters.solucion.vo.AutocompleteFormulario> CiudadDepartamentoPaisFormAsync(co.itmasters.solucion.vo.AutocompleteFormulario Autocomplete);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonaService/CiudadAutocompleteForm", ReplyAction="http://tempuri.org/IPersonaService/CiudadAutocompleteFormResponse")]
        string[] CiudadAutocompleteForm(co.itmasters.solucion.vo.AutocompleteFormulario Autocomplete);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonaService/CiudadAutocompleteForm", ReplyAction="http://tempuri.org/IPersonaService/CiudadAutocompleteFormResponse")]
        System.Threading.Tasks.Task<string[]> CiudadAutocompleteFormAsync(co.itmasters.solucion.vo.AutocompleteFormulario Autocomplete);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonaService/Persona_DatosBasicos", ReplyAction="http://tempuri.org/IPersonaService/Persona_DatosBasicosResponse")]
        co.itmasters.solucion.vo.PersonaVO[] Persona_DatosBasicos(co.itmasters.solucion.vo.PersonaVO pPersona);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonaService/Persona_DatosBasicos", ReplyAction="http://tempuri.org/IPersonaService/Persona_DatosBasicosResponse")]
        System.Threading.Tasks.Task<co.itmasters.solucion.vo.PersonaVO[]> Persona_DatosBasicosAsync(co.itmasters.solucion.vo.PersonaVO pPersona);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonaService/Persona_DatosBasicosPersonas", ReplyAction="http://tempuri.org/IPersonaService/Persona_DatosBasicosPersonasResponse")]
        co.itmasters.solucion.vo.PersonaVO[] Persona_DatosBasicosPersonas(co.itmasters.solucion.vo.PersonaVO pPersona);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonaService/Persona_DatosBasicosPersonas", ReplyAction="http://tempuri.org/IPersonaService/Persona_DatosBasicosPersonasResponse")]
        System.Threading.Tasks.Task<co.itmasters.solucion.vo.PersonaVO[]> Persona_DatosBasicosPersonasAsync(co.itmasters.solucion.vo.PersonaVO pPersona);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonaService/Guardar_PersonaTercero", ReplyAction="http://tempuri.org/IPersonaService/Guardar_PersonaTerceroResponse")]
        void Guardar_PersonaTercero(co.itmasters.solucion.vo.PersonaVO pPersona);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonaService/Guardar_PersonaTercero", ReplyAction="http://tempuri.org/IPersonaService/Guardar_PersonaTerceroResponse")]
        System.Threading.Tasks.Task Guardar_PersonaTerceroAsync(co.itmasters.solucion.vo.PersonaVO pPersona);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonaService/Guardar_CambiarClave", ReplyAction="http://tempuri.org/IPersonaService/Guardar_CambiarClaveResponse")]
        void Guardar_CambiarClave(co.itmasters.solucion.vo.FuncionarioVO pPersona);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonaService/Guardar_CambiarClave", ReplyAction="http://tempuri.org/IPersonaService/Guardar_CambiarClaveResponse")]
        System.Threading.Tasks.Task Guardar_CambiarClaveAsync(co.itmasters.solucion.vo.FuncionarioVO pPersona);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonaService/Buscar_Persona", ReplyAction="http://tempuri.org/IPersonaService/Buscar_PersonaResponse")]
        co.itmasters.solucion.vo.PersonaVO Buscar_Persona(co.itmasters.solucion.vo.PersonaVO pPersona);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonaService/Buscar_Persona", ReplyAction="http://tempuri.org/IPersonaService/Buscar_PersonaResponse")]
        System.Threading.Tasks.Task<co.itmasters.solucion.vo.PersonaVO> Buscar_PersonaAsync(co.itmasters.solucion.vo.PersonaVO pPersona);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonaService/Buscar_personaId", ReplyAction="http://tempuri.org/IPersonaService/Buscar_personaIdResponse")]
        co.itmasters.solucion.vo.PersonaVO Buscar_personaId(co.itmasters.solucion.vo.PersonaVO ppersona);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonaService/Buscar_personaId", ReplyAction="http://tempuri.org/IPersonaService/Buscar_personaIdResponse")]
        System.Threading.Tasks.Task<co.itmasters.solucion.vo.PersonaVO> Buscar_personaIdAsync(co.itmasters.solucion.vo.PersonaVO ppersona);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonaService/Buscar_personaDatosModificados", ReplyAction="http://tempuri.org/IPersonaService/Buscar_personaDatosModificadosResponse")]
        co.itmasters.solucion.vo.PersonaVO[] Buscar_personaDatosModificados(co.itmasters.solucion.vo.PersonaVO ppersona);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonaService/Buscar_personaDatosModificados", ReplyAction="http://tempuri.org/IPersonaService/Buscar_personaDatosModificadosResponse")]
        System.Threading.Tasks.Task<co.itmasters.solucion.vo.PersonaVO[]> Buscar_personaDatosModificadosAsync(co.itmasters.solucion.vo.PersonaVO ppersona);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonaService/Guardar_Funcionario", ReplyAction="http://tempuri.org/IPersonaService/Guardar_FuncionarioResponse")]
        void Guardar_Funcionario(co.itmasters.solucion.vo.FuncionarioVO funcionario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonaService/Guardar_Funcionario", ReplyAction="http://tempuri.org/IPersonaService/Guardar_FuncionarioResponse")]
        System.Threading.Tasks.Task Guardar_FuncionarioAsync(co.itmasters.solucion.vo.FuncionarioVO funcionario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonaService/Buscar_Funcionario", ReplyAction="http://tempuri.org/IPersonaService/Buscar_FuncionarioResponse")]
        co.itmasters.solucion.vo.FuncionarioVO Buscar_Funcionario(co.itmasters.solucion.vo.FuncionarioVO funcionario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonaService/Buscar_Funcionario", ReplyAction="http://tempuri.org/IPersonaService/Buscar_FuncionarioResponse")]
        System.Threading.Tasks.Task<co.itmasters.solucion.vo.FuncionarioVO> Buscar_FuncionarioAsync(co.itmasters.solucion.vo.FuncionarioVO funcionario);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPersonaServiceChannel : co.itmasters.solucion.web.PersonaService.IPersonaService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PersonaServiceClient : System.ServiceModel.ClientBase<co.itmasters.solucion.web.PersonaService.IPersonaService>, co.itmasters.solucion.web.PersonaService.IPersonaService {
        
        public PersonaServiceClient() {
        }
        
        public PersonaServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PersonaServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PersonaServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PersonaServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void PersonaDatosBasicos_Update(co.itmasters.solucion.vo.PersonaVO pPersona) {
            base.Channel.PersonaDatosBasicos_Update(pPersona);
        }
        
        public System.Threading.Tasks.Task PersonaDatosBasicos_UpdateAsync(co.itmasters.solucion.vo.PersonaVO pPersona) {
            return base.Channel.PersonaDatosBasicos_UpdateAsync(pPersona);
        }
        
        public void PersonaAcademia_Update(co.itmasters.solucion.vo.PersonaAcademiaVO pPersona) {
            base.Channel.PersonaAcademia_Update(pPersona);
        }
        
        public System.Threading.Tasks.Task PersonaAcademia_UpdateAsync(co.itmasters.solucion.vo.PersonaAcademiaVO pPersona) {
            return base.Channel.PersonaAcademia_UpdateAsync(pPersona);
        }
        
        public void PersonaExperiencia_Update(co.itmasters.solucion.vo.PersonaExperienciaVO pPersona) {
            base.Channel.PersonaExperiencia_Update(pPersona);
        }
        
        public System.Threading.Tasks.Task PersonaExperiencia_UpdateAsync(co.itmasters.solucion.vo.PersonaExperienciaVO pPersona) {
            return base.Channel.PersonaExperiencia_UpdateAsync(pPersona);
        }
        
        public void PersonaAptitud_Update(co.itmasters.solucion.vo.PersonaAptitudVO pPersona) {
            base.Channel.PersonaAptitud_Update(pPersona);
        }
        
        public System.Threading.Tasks.Task PersonaAptitud_UpdateAsync(co.itmasters.solucion.vo.PersonaAptitudVO pPersona) {
            return base.Channel.PersonaAptitud_UpdateAsync(pPersona);
        }
        
        public co.itmasters.solucion.vo.AutocompleteActividadEconomica[] ActEconomicaAutocomplete(co.itmasters.solucion.vo.AutocompleteActividadEconomica Act) {
            return base.Channel.ActEconomicaAutocomplete(Act);
        }
        
        public System.Threading.Tasks.Task<co.itmasters.solucion.vo.AutocompleteActividadEconomica[]> ActEconomicaAutocompleteAsync(co.itmasters.solucion.vo.AutocompleteActividadEconomica Act) {
            return base.Channel.ActEconomicaAutocompleteAsync(Act);
        }
        
        public co.itmasters.solucion.vo.AutocompleteFormulario CiudadDepartamentoPaisForm(co.itmasters.solucion.vo.AutocompleteFormulario Autocomplete) {
            return base.Channel.CiudadDepartamentoPaisForm(Autocomplete);
        }
        
        public System.Threading.Tasks.Task<co.itmasters.solucion.vo.AutocompleteFormulario> CiudadDepartamentoPaisFormAsync(co.itmasters.solucion.vo.AutocompleteFormulario Autocomplete) {
            return base.Channel.CiudadDepartamentoPaisFormAsync(Autocomplete);
        }
        
        public string[] CiudadAutocompleteForm(co.itmasters.solucion.vo.AutocompleteFormulario Autocomplete) {
            return base.Channel.CiudadAutocompleteForm(Autocomplete);
        }
        
        public System.Threading.Tasks.Task<string[]> CiudadAutocompleteFormAsync(co.itmasters.solucion.vo.AutocompleteFormulario Autocomplete) {
            return base.Channel.CiudadAutocompleteFormAsync(Autocomplete);
        }
        
        public co.itmasters.solucion.vo.PersonaVO[] Persona_DatosBasicos(co.itmasters.solucion.vo.PersonaVO pPersona) {
            return base.Channel.Persona_DatosBasicos(pPersona);
        }
        
        public System.Threading.Tasks.Task<co.itmasters.solucion.vo.PersonaVO[]> Persona_DatosBasicosAsync(co.itmasters.solucion.vo.PersonaVO pPersona) {
            return base.Channel.Persona_DatosBasicosAsync(pPersona);
        }
        
        public co.itmasters.solucion.vo.PersonaVO[] Persona_DatosBasicosPersonas(co.itmasters.solucion.vo.PersonaVO pPersona) {
            return base.Channel.Persona_DatosBasicosPersonas(pPersona);
        }
        
        public System.Threading.Tasks.Task<co.itmasters.solucion.vo.PersonaVO[]> Persona_DatosBasicosPersonasAsync(co.itmasters.solucion.vo.PersonaVO pPersona) {
            return base.Channel.Persona_DatosBasicosPersonasAsync(pPersona);
        }
        
        public void Guardar_PersonaTercero(co.itmasters.solucion.vo.PersonaVO pPersona) {
            base.Channel.Guardar_PersonaTercero(pPersona);
        }
        
        public System.Threading.Tasks.Task Guardar_PersonaTerceroAsync(co.itmasters.solucion.vo.PersonaVO pPersona) {
            return base.Channel.Guardar_PersonaTerceroAsync(pPersona);
        }
        
        public void Guardar_CambiarClave(co.itmasters.solucion.vo.FuncionarioVO pPersona) {
            base.Channel.Guardar_CambiarClave(pPersona);
        }
        
        public System.Threading.Tasks.Task Guardar_CambiarClaveAsync(co.itmasters.solucion.vo.FuncionarioVO pPersona) {
            return base.Channel.Guardar_CambiarClaveAsync(pPersona);
        }
        
        public co.itmasters.solucion.vo.PersonaVO Buscar_Persona(co.itmasters.solucion.vo.PersonaVO pPersona) {
            return base.Channel.Buscar_Persona(pPersona);
        }
        
        public System.Threading.Tasks.Task<co.itmasters.solucion.vo.PersonaVO> Buscar_PersonaAsync(co.itmasters.solucion.vo.PersonaVO pPersona) {
            return base.Channel.Buscar_PersonaAsync(pPersona);
        }
        
        public co.itmasters.solucion.vo.PersonaVO Buscar_personaId(co.itmasters.solucion.vo.PersonaVO ppersona) {
            return base.Channel.Buscar_personaId(ppersona);
        }
        
        public System.Threading.Tasks.Task<co.itmasters.solucion.vo.PersonaVO> Buscar_personaIdAsync(co.itmasters.solucion.vo.PersonaVO ppersona) {
            return base.Channel.Buscar_personaIdAsync(ppersona);
        }
        
        public co.itmasters.solucion.vo.PersonaVO[] Buscar_personaDatosModificados(co.itmasters.solucion.vo.PersonaVO ppersona) {
            return base.Channel.Buscar_personaDatosModificados(ppersona);
        }
        
        public System.Threading.Tasks.Task<co.itmasters.solucion.vo.PersonaVO[]> Buscar_personaDatosModificadosAsync(co.itmasters.solucion.vo.PersonaVO ppersona) {
            return base.Channel.Buscar_personaDatosModificadosAsync(ppersona);
        }
        
        public void Guardar_Funcionario(co.itmasters.solucion.vo.FuncionarioVO funcionario) {
            base.Channel.Guardar_Funcionario(funcionario);
        }
        
        public System.Threading.Tasks.Task Guardar_FuncionarioAsync(co.itmasters.solucion.vo.FuncionarioVO funcionario) {
            return base.Channel.Guardar_FuncionarioAsync(funcionario);
        }
        
        public co.itmasters.solucion.vo.FuncionarioVO Buscar_Funcionario(co.itmasters.solucion.vo.FuncionarioVO funcionario) {
            return base.Channel.Buscar_Funcionario(funcionario);
        }
        
        public System.Threading.Tasks.Task<co.itmasters.solucion.vo.FuncionarioVO> Buscar_FuncionarioAsync(co.itmasters.solucion.vo.FuncionarioVO funcionario) {
            return base.Channel.Buscar_FuncionarioAsync(funcionario);
        }
    }
}
