//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace co.itmasters.solucion.web.MercadoPagoService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MercadoPagoService.IMercadoPagoService")]
    public interface IMercadoPagoService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMercadoPagoService/RecibirInformacionBackUrl", ReplyAction="http://tempuri.org/IMercadoPagoService/RecibirInformacionBackUrlResponse")]
        void RecibirInformacionBackUrl(string preferenceId, string status, string collection_id, string payment_id, string external_reference, string payment_type, string merchant_order_id, string site_id, string processing_mode, string merchant_account_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMercadoPagoService/RecibirInformacionBackUrl", ReplyAction="http://tempuri.org/IMercadoPagoService/RecibirInformacionBackUrlResponse")]
        System.Threading.Tasks.Task RecibirInformacionBackUrlAsync(string preferenceId, string status, string collection_id, string payment_id, string external_reference, string payment_type, string merchant_order_id, string site_id, string processing_mode, string merchant_account_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMercadoPagoService/ProcessNotification", ReplyAction="http://tempuri.org/IMercadoPagoService/ProcessNotificationResponse")]
        void ProcessNotification(System.IO.Stream inputStream);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMercadoPagoService/ProcessNotification", ReplyAction="http://tempuri.org/IMercadoPagoService/ProcessNotificationResponse")]
        System.Threading.Tasks.Task ProcessNotificationAsync(System.IO.Stream inputStream);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMercadoPagoServiceChannel : co.itmasters.solucion.web.MercadoPagoService.IMercadoPagoService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MercadoPagoServiceClient : System.ServiceModel.ClientBase<co.itmasters.solucion.web.MercadoPagoService.IMercadoPagoService>, co.itmasters.solucion.web.MercadoPagoService.IMercadoPagoService {
        
        public MercadoPagoServiceClient() {
        }
        
        public MercadoPagoServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MercadoPagoServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MercadoPagoServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MercadoPagoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void RecibirInformacionBackUrl(string preferenceId, string status, string collection_id, string payment_id, string external_reference, string payment_type, string merchant_order_id, string site_id, string processing_mode, string merchant_account_id) {
            base.Channel.RecibirInformacionBackUrl(preferenceId, status, collection_id, payment_id, external_reference, payment_type, merchant_order_id, site_id, processing_mode, merchant_account_id);
        }
        
        public System.Threading.Tasks.Task RecibirInformacionBackUrlAsync(string preferenceId, string status, string collection_id, string payment_id, string external_reference, string payment_type, string merchant_order_id, string site_id, string processing_mode, string merchant_account_id) {
            return base.Channel.RecibirInformacionBackUrlAsync(preferenceId, status, collection_id, payment_id, external_reference, payment_type, merchant_order_id, site_id, processing_mode, merchant_account_id);
        }
        
        public void ProcessNotification(System.IO.Stream inputStream) {
            base.Channel.ProcessNotification(inputStream);
        }
        
        public System.Threading.Tasks.Task ProcessNotificationAsync(System.IO.Stream inputStream) {
            return base.Channel.ProcessNotificationAsync(inputStream);
        }
    }
}
