//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace co.itmasters.solucion.web.MercadoPagoService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MercadoPagoService.IMercadoPagoService")]
    public interface IMercadoPagoService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMercadoPagoService/UpdatePayment", ReplyAction="http://tempuri.org/IMercadoPagoService/UpdatePaymentResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(co.itmasters.solucion.vo.AdditionalInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(co.itmasters.solucion.vo.Item[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(co.itmasters.solucion.vo.Item))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(co.itmasters.solucion.vo.Card))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(co.itmasters.solucion.vo.Cardholder))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(co.itmasters.solucion.vo.Identification))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(co.itmasters.solucion.vo.ChargesDetails[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(co.itmasters.solucion.vo.ChargesDetails))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(co.itmasters.solucion.vo.Accounts))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(co.itmasters.solucion.vo.Amounts))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(co.itmasters.solucion.vo.PaymentMethod))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(co.itmasters.solucion.vo.Data))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(co.itmasters.solucion.vo.RoutingData))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<string, object>))]
        void UpdatePayment(co.itmasters.solucion.vo.PaymentVO payment, string estadoPago);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMercadoPagoService/UpdatePayment", ReplyAction="http://tempuri.org/IMercadoPagoService/UpdatePaymentResponse")]
        System.Threading.Tasks.Task UpdatePaymentAsync(co.itmasters.solucion.vo.PaymentVO payment, string estadoPago);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMercadoPagoService/GetPayment", ReplyAction="http://tempuri.org/IMercadoPagoService/GetPaymentResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(co.itmasters.solucion.vo.AdditionalInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(co.itmasters.solucion.vo.Item[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(co.itmasters.solucion.vo.Item))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(co.itmasters.solucion.vo.Card))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(co.itmasters.solucion.vo.Cardholder))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(co.itmasters.solucion.vo.Identification))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(co.itmasters.solucion.vo.ChargesDetails[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(co.itmasters.solucion.vo.ChargesDetails))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(co.itmasters.solucion.vo.Accounts))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(co.itmasters.solucion.vo.Amounts))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(co.itmasters.solucion.vo.PaymentMethod))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(co.itmasters.solucion.vo.Data))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(co.itmasters.solucion.vo.RoutingData))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<string, object>))]
        co.itmasters.solucion.vo.PaymentVO GetPayment(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMercadoPagoService/GetPayment", ReplyAction="http://tempuri.org/IMercadoPagoService/GetPaymentResponse")]
        System.Threading.Tasks.Task<co.itmasters.solucion.vo.PaymentVO> GetPaymentAsync(string id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMercadoPagoServiceChannel : co.itmasters.solucion.web.MercadoPagoService.IMercadoPagoService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MercadoPagoServiceClient : System.ServiceModel.ClientBase<co.itmasters.solucion.web.MercadoPagoService.IMercadoPagoService>, co.itmasters.solucion.web.MercadoPagoService.IMercadoPagoService {
        
        public MercadoPagoServiceClient() {
        }
        
        public MercadoPagoServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MercadoPagoServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MercadoPagoServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MercadoPagoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void UpdatePayment(co.itmasters.solucion.vo.PaymentVO payment, string estadoPago) {
            base.Channel.UpdatePayment(payment, estadoPago);
        }
        
        public System.Threading.Tasks.Task UpdatePaymentAsync(co.itmasters.solucion.vo.PaymentVO payment, string estadoPago) {
            return base.Channel.UpdatePaymentAsync(payment, estadoPago);
        }
        
        public co.itmasters.solucion.vo.PaymentVO GetPayment(string id) {
            return base.Channel.GetPayment(id);
        }
        
        public System.Threading.Tasks.Task<co.itmasters.solucion.vo.PaymentVO> GetPaymentAsync(string id) {
            return base.Channel.GetPaymentAsync(id);
        }
    }
}
