//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace co.itmasters.solucion.web.com.zonapagos.www1 {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ZPagosSoap", Namespace="http://www.zonapagos.com")]
    public partial class ZPagos : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback inicio_pagoV2OperationCompleted;
        
        private System.Threading.SendOrPostCallback inicio_pagoV3OperationCompleted;
        
        private System.Threading.SendOrPostCallback inicio_pagoV4OperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ZPagos() {
            this.Url = global::co.itmasters.solucion.web.Properties.Settings.Default.co_itmasters_academics_web_com_zonapagos_www1_ZPagos;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event inicio_pagoV2CompletedEventHandler inicio_pagoV2Completed;
        
        /// <remarks/>
        public event inicio_pagoV3CompletedEventHandler inicio_pagoV3Completed;
        
        /// <remarks/>
        public event inicio_pagoV4CompletedEventHandler inicio_pagoV4Completed;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.zonapagos.com/inicio_pagoV2", RequestNamespace="http://www.zonapagos.com", ResponseNamespace="http://www.zonapagos.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string inicio_pagoV2(
                    int id_tienda, 
                    string clave, 
                    double total_con_iva, 
                    double valor_iva, 
                    string id_pago, 
                    string descripcion_pago, 
                    string email, 
                    string id_cliente, 
                    string tipo_id, 
                    string nombre_cliente, 
                    string apellido_cliente, 
                    string telefono_cliente, 
                    string info_opcional1, 
                    string info_opcional2, 
                    string info_opcional3, 
                    string codigo_servicio_principal, 
                    string[] lista_codigos_servicio_multicredito, 
                    string[] lista_nit_codigos_servicio_multicredito, 
                    double[] lista_valores_con_iva, 
                    double[] lista_valores_iva, 
                    int total_codigos_servicio) {
            object[] results = this.Invoke("inicio_pagoV2", new object[] {
                        id_tienda,
                        clave,
                        total_con_iva,
                        valor_iva,
                        id_pago,
                        descripcion_pago,
                        email,
                        id_cliente,
                        tipo_id,
                        nombre_cliente,
                        apellido_cliente,
                        telefono_cliente,
                        info_opcional1,
                        info_opcional2,
                        info_opcional3,
                        codigo_servicio_principal,
                        lista_codigos_servicio_multicredito,
                        lista_nit_codigos_servicio_multicredito,
                        lista_valores_con_iva,
                        lista_valores_iva,
                        total_codigos_servicio});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void inicio_pagoV2Async(
                    int id_tienda, 
                    string clave, 
                    double total_con_iva, 
                    double valor_iva, 
                    string id_pago, 
                    string descripcion_pago, 
                    string email, 
                    string id_cliente, 
                    string tipo_id, 
                    string nombre_cliente, 
                    string apellido_cliente, 
                    string telefono_cliente, 
                    string info_opcional1, 
                    string info_opcional2, 
                    string info_opcional3, 
                    string codigo_servicio_principal, 
                    string[] lista_codigos_servicio_multicredito, 
                    string[] lista_nit_codigos_servicio_multicredito, 
                    double[] lista_valores_con_iva, 
                    double[] lista_valores_iva, 
                    int total_codigos_servicio) {
            this.inicio_pagoV2Async(id_tienda, clave, total_con_iva, valor_iva, id_pago, descripcion_pago, email, id_cliente, tipo_id, nombre_cliente, apellido_cliente, telefono_cliente, info_opcional1, info_opcional2, info_opcional3, codigo_servicio_principal, lista_codigos_servicio_multicredito, lista_nit_codigos_servicio_multicredito, lista_valores_con_iva, lista_valores_iva, total_codigos_servicio, null);
        }
        
        /// <remarks/>
        public void inicio_pagoV2Async(
                    int id_tienda, 
                    string clave, 
                    double total_con_iva, 
                    double valor_iva, 
                    string id_pago, 
                    string descripcion_pago, 
                    string email, 
                    string id_cliente, 
                    string tipo_id, 
                    string nombre_cliente, 
                    string apellido_cliente, 
                    string telefono_cliente, 
                    string info_opcional1, 
                    string info_opcional2, 
                    string info_opcional3, 
                    string codigo_servicio_principal, 
                    string[] lista_codigos_servicio_multicredito, 
                    string[] lista_nit_codigos_servicio_multicredito, 
                    double[] lista_valores_con_iva, 
                    double[] lista_valores_iva, 
                    int total_codigos_servicio, 
                    object userState) {
            if ((this.inicio_pagoV2OperationCompleted == null)) {
                this.inicio_pagoV2OperationCompleted = new System.Threading.SendOrPostCallback(this.Oninicio_pagoV2OperationCompleted);
            }
            this.InvokeAsync("inicio_pagoV2", new object[] {
                        id_tienda,
                        clave,
                        total_con_iva,
                        valor_iva,
                        id_pago,
                        descripcion_pago,
                        email,
                        id_cliente,
                        tipo_id,
                        nombre_cliente,
                        apellido_cliente,
                        telefono_cliente,
                        info_opcional1,
                        info_opcional2,
                        info_opcional3,
                        codigo_servicio_principal,
                        lista_codigos_servicio_multicredito,
                        lista_nit_codigos_servicio_multicredito,
                        lista_valores_con_iva,
                        lista_valores_iva,
                        total_codigos_servicio}, this.inicio_pagoV2OperationCompleted, userState);
        }
        
        private void Oninicio_pagoV2OperationCompleted(object arg) {
            if ((this.inicio_pagoV2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.inicio_pagoV2Completed(this, new inicio_pagoV2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.zonapagos.com/inicio_pagoV3", RequestNamespace="http://www.zonapagos.com", ResponseNamespace="http://www.zonapagos.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string inicio_pagoV3(
                    int id_tienda, 
                    string clave, 
                    double total_con_iva, 
                    double valor_iva, 
                    string id_pago, 
                    string descripcion_pago, 
                    string email, 
                    string id_cliente, 
                    string tipo_id, 
                    string nombre_cliente, 
                    string apellido_cliente, 
                    string telefono_cliente, 
                    string info_opcional1, 
                    string info_opcional2, 
                    string info_opcional3, 
                    string codigo_servicio_principal, 
                    string[] lista_codigos_servicio_multicredito, 
                    string[] lista_nit_codigos_servicio_multicredito, 
                    double[] lista_valores_con_iva, 
                    double[] lista_valores_iva, 
                    int total_codigos_servicio, 
                    string archivo_adjunto_nombre_original, 
                    string archivo_adjunto_nombre_guardado, 
                    string[] lista_info_opcional) {
            object[] results = this.Invoke("inicio_pagoV3", new object[] {
                        id_tienda,
                        clave,
                        total_con_iva,
                        valor_iva,
                        id_pago,
                        descripcion_pago,
                        email,
                        id_cliente,
                        tipo_id,
                        nombre_cliente,
                        apellido_cliente,
                        telefono_cliente,
                        info_opcional1,
                        info_opcional2,
                        info_opcional3,
                        codigo_servicio_principal,
                        lista_codigos_servicio_multicredito,
                        lista_nit_codigos_servicio_multicredito,
                        lista_valores_con_iva,
                        lista_valores_iva,
                        total_codigos_servicio,
                        archivo_adjunto_nombre_original,
                        archivo_adjunto_nombre_guardado,
                        lista_info_opcional});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void inicio_pagoV3Async(
                    int id_tienda, 
                    string clave, 
                    double total_con_iva, 
                    double valor_iva, 
                    string id_pago, 
                    string descripcion_pago, 
                    string email, 
                    string id_cliente, 
                    string tipo_id, 
                    string nombre_cliente, 
                    string apellido_cliente, 
                    string telefono_cliente, 
                    string info_opcional1, 
                    string info_opcional2, 
                    string info_opcional3, 
                    string codigo_servicio_principal, 
                    string[] lista_codigos_servicio_multicredito, 
                    string[] lista_nit_codigos_servicio_multicredito, 
                    double[] lista_valores_con_iva, 
                    double[] lista_valores_iva, 
                    int total_codigos_servicio, 
                    string archivo_adjunto_nombre_original, 
                    string archivo_adjunto_nombre_guardado, 
                    string[] lista_info_opcional) {
            this.inicio_pagoV3Async(id_tienda, clave, total_con_iva, valor_iva, id_pago, descripcion_pago, email, id_cliente, tipo_id, nombre_cliente, apellido_cliente, telefono_cliente, info_opcional1, info_opcional2, info_opcional3, codigo_servicio_principal, lista_codigos_servicio_multicredito, lista_nit_codigos_servicio_multicredito, lista_valores_con_iva, lista_valores_iva, total_codigos_servicio, archivo_adjunto_nombre_original, archivo_adjunto_nombre_guardado, lista_info_opcional, null);
        }
        
        /// <remarks/>
        public void inicio_pagoV3Async(
                    int id_tienda, 
                    string clave, 
                    double total_con_iva, 
                    double valor_iva, 
                    string id_pago, 
                    string descripcion_pago, 
                    string email, 
                    string id_cliente, 
                    string tipo_id, 
                    string nombre_cliente, 
                    string apellido_cliente, 
                    string telefono_cliente, 
                    string info_opcional1, 
                    string info_opcional2, 
                    string info_opcional3, 
                    string codigo_servicio_principal, 
                    string[] lista_codigos_servicio_multicredito, 
                    string[] lista_nit_codigos_servicio_multicredito, 
                    double[] lista_valores_con_iva, 
                    double[] lista_valores_iva, 
                    int total_codigos_servicio, 
                    string archivo_adjunto_nombre_original, 
                    string archivo_adjunto_nombre_guardado, 
                    string[] lista_info_opcional, 
                    object userState) {
            if ((this.inicio_pagoV3OperationCompleted == null)) {
                this.inicio_pagoV3OperationCompleted = new System.Threading.SendOrPostCallback(this.Oninicio_pagoV3OperationCompleted);
            }
            this.InvokeAsync("inicio_pagoV3", new object[] {
                        id_tienda,
                        clave,
                        total_con_iva,
                        valor_iva,
                        id_pago,
                        descripcion_pago,
                        email,
                        id_cliente,
                        tipo_id,
                        nombre_cliente,
                        apellido_cliente,
                        telefono_cliente,
                        info_opcional1,
                        info_opcional2,
                        info_opcional3,
                        codigo_servicio_principal,
                        lista_codigos_servicio_multicredito,
                        lista_nit_codigos_servicio_multicredito,
                        lista_valores_con_iva,
                        lista_valores_iva,
                        total_codigos_servicio,
                        archivo_adjunto_nombre_original,
                        archivo_adjunto_nombre_guardado,
                        lista_info_opcional}, this.inicio_pagoV3OperationCompleted, userState);
        }
        
        private void Oninicio_pagoV3OperationCompleted(object arg) {
            if ((this.inicio_pagoV3Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.inicio_pagoV3Completed(this, new inicio_pagoV3CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.zonapagos.com/inicio_pagoV4", RequestNamespace="http://www.zonapagos.com", ResponseNamespace="http://www.zonapagos.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string inicio_pagoV4(
                    int id_tienda, 
                    string clave, 
                    double total_con_iva, 
                    double valor_iva, 
                    string id_pago, 
                    string descripcion_pago, 
                    string email, 
                    string id_cliente, 
                    string tipo_id, 
                    string nombre_cliente, 
                    string apellido_cliente, 
                    string telefono_cliente, 
                    string info_opcional1, 
                    string info_opcional2, 
                    string info_opcional3, 
                    string codigo_servicio_principal, 
                    string[] lista_codigos_servicio_multicredito, 
                    string[] lista_nit_codigos_servicio_multicredito, 
                    double[] lista_valores_con_iva, 
                    double[] lista_valores_iva, 
                    int total_codigos_servicio, 
                    string lista_info_opcional_codigo, 
                    string lista_info_opcional_valor, 
                    ref string[] lista_respuesta) {
            object[] results = this.Invoke("inicio_pagoV4", new object[] {
                        id_tienda,
                        clave,
                        total_con_iva,
                        valor_iva,
                        id_pago,
                        descripcion_pago,
                        email,
                        id_cliente,
                        tipo_id,
                        nombre_cliente,
                        apellido_cliente,
                        telefono_cliente,
                        info_opcional1,
                        info_opcional2,
                        info_opcional3,
                        codigo_servicio_principal,
                        lista_codigos_servicio_multicredito,
                        lista_nit_codigos_servicio_multicredito,
                        lista_valores_con_iva,
                        lista_valores_iva,
                        total_codigos_servicio,
                        lista_info_opcional_codigo,
                        lista_info_opcional_valor,
                        lista_respuesta});
            lista_respuesta = ((string[])(results[1]));
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void inicio_pagoV4Async(
                    int id_tienda, 
                    string clave, 
                    double total_con_iva, 
                    double valor_iva, 
                    string id_pago, 
                    string descripcion_pago, 
                    string email, 
                    string id_cliente, 
                    string tipo_id, 
                    string nombre_cliente, 
                    string apellido_cliente, 
                    string telefono_cliente, 
                    string info_opcional1, 
                    string info_opcional2, 
                    string info_opcional3, 
                    string codigo_servicio_principal, 
                    string[] lista_codigos_servicio_multicredito, 
                    string[] lista_nit_codigos_servicio_multicredito, 
                    double[] lista_valores_con_iva, 
                    double[] lista_valores_iva, 
                    int total_codigos_servicio, 
                    string lista_info_opcional_codigo, 
                    string lista_info_opcional_valor, 
                    string[] lista_respuesta) {
            this.inicio_pagoV4Async(id_tienda, clave, total_con_iva, valor_iva, id_pago, descripcion_pago, email, id_cliente, tipo_id, nombre_cliente, apellido_cliente, telefono_cliente, info_opcional1, info_opcional2, info_opcional3, codigo_servicio_principal, lista_codigos_servicio_multicredito, lista_nit_codigos_servicio_multicredito, lista_valores_con_iva, lista_valores_iva, total_codigos_servicio, lista_info_opcional_codigo, lista_info_opcional_valor, lista_respuesta, null);
        }
        
        /// <remarks/>
        public void inicio_pagoV4Async(
                    int id_tienda, 
                    string clave, 
                    double total_con_iva, 
                    double valor_iva, 
                    string id_pago, 
                    string descripcion_pago, 
                    string email, 
                    string id_cliente, 
                    string tipo_id, 
                    string nombre_cliente, 
                    string apellido_cliente, 
                    string telefono_cliente, 
                    string info_opcional1, 
                    string info_opcional2, 
                    string info_opcional3, 
                    string codigo_servicio_principal, 
                    string[] lista_codigos_servicio_multicredito, 
                    string[] lista_nit_codigos_servicio_multicredito, 
                    double[] lista_valores_con_iva, 
                    double[] lista_valores_iva, 
                    int total_codigos_servicio, 
                    string lista_info_opcional_codigo, 
                    string lista_info_opcional_valor, 
                    string[] lista_respuesta, 
                    object userState) {
            if ((this.inicio_pagoV4OperationCompleted == null)) {
                this.inicio_pagoV4OperationCompleted = new System.Threading.SendOrPostCallback(this.Oninicio_pagoV4OperationCompleted);
            }
            this.InvokeAsync("inicio_pagoV4", new object[] {
                        id_tienda,
                        clave,
                        total_con_iva,
                        valor_iva,
                        id_pago,
                        descripcion_pago,
                        email,
                        id_cliente,
                        tipo_id,
                        nombre_cliente,
                        apellido_cliente,
                        telefono_cliente,
                        info_opcional1,
                        info_opcional2,
                        info_opcional3,
                        codigo_servicio_principal,
                        lista_codigos_servicio_multicredito,
                        lista_nit_codigos_servicio_multicredito,
                        lista_valores_con_iva,
                        lista_valores_iva,
                        total_codigos_servicio,
                        lista_info_opcional_codigo,
                        lista_info_opcional_valor,
                        lista_respuesta}, this.inicio_pagoV4OperationCompleted, userState);
        }
        
        private void Oninicio_pagoV4OperationCompleted(object arg) {
            if ((this.inicio_pagoV4Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.inicio_pagoV4Completed(this, new inicio_pagoV4CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void inicio_pagoV2CompletedEventHandler(object sender, inicio_pagoV2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class inicio_pagoV2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal inicio_pagoV2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void inicio_pagoV3CompletedEventHandler(object sender, inicio_pagoV3CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class inicio_pagoV3CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal inicio_pagoV3CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void inicio_pagoV4CompletedEventHandler(object sender, inicio_pagoV4CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class inicio_pagoV4CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal inicio_pagoV4CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string[] lista_respuesta {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[1]));
            }
        }
    }
}

#pragma warning restore 1591