name: Build and Publish

on:
  push:
    branches:
      - main  # Especifica la rama en la que deseas que se desencadene el flujo de trabajo

jobs:
  build-and-publish:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Descarga tu código fuente en la máquina de GitHub Actions

    - name: Setup .NET Framework
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '4.6.x'  # Especifica la versión de .NET Framework que necesitas

    - name: Install MSBuild
      run: choco install visualstudio2019buildtools --package-parameters "--add Microsoft.VisualStudio.Component.MSBuild --add Microsoft.VisualStudio.Component.VC.Tools.x86.x64"

    - name: Restore dependencies
      run: nuget restore

    - name: Build
      run: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\MSBuild\\Current\\Bin\\MSBuild.exe /p:Configuration=Release"  # Compila el proyecto en modo Release

    - name: Prepare ZIP file
      run: Compress-Archive -Path "path/to/your/application" -DestinationPath "published-app.zip"

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: published-app
        path: ./published-app.zip  # Sube el archivo ZIP como artefacto
